
project_id = "ehzhosyzybzxhvhisojh"
app_id = "1"

[functions.threshold-checker]
verify_jwt = false

[functions.init-admin-access]
verify_jwt = false

[functions.extract-zip]
verify_jwt = false

[functions.create-documents-bucket]
verify_jwt = false
