import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle } from '../../ui/card';
import { Button } from '../../ui/button';
import { FileText, Download, Eye } from 'lucide-react';
export const ReportViewer = ({ reports, onView, onDownload, }) => {
    if (!reports || reports.length === 0) {
        return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Reports" }) }), _jsx(CardContent, { children: _jsxs("div", { className: "flex flex-col items-center justify-center p-8 text-center", children: [_jsx(FileText, { className: "h-16 w-16 text-gray-300 mb-4" }), _jsx("p", { className: "text-lg font-medium text-gray-500", children: "No reports available" }), _jsx("p", { className: "text-sm text-gray-400 mt-2", children: "Reports will be displayed here once they are available" })] }) })] }));
    }
    return (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Reports" }) }), _jsx(CardContent, { children: _jsx("div", { className: "overflow-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b", children: [_jsx("th", { className: "text-left p-2 font-medium", children: "Report Title" }), _jsx("th", { className: "text-left p-2 font-medium", children: "Date" }), _jsx("th", { className: "text-left p-2 font-medium", children: "Type" }), _jsx("th", { className: "text-right p-2 font-medium", children: "Actions" })] }) }), _jsx("tbody", { children: reports.map((report) => (_jsxs("tr", { className: "border-b hover:bg-gray-50", children: [_jsx("td", { className: "p-2", children: _jsxs("div", { className: "flex items-center", children: [_jsx(FileText, { className: "h-4 w-4 mr-2 text-blue-500" }), _jsx("span", { children: report.title })] }) }), _jsx("td", { className: "p-2", children: report.date }), _jsx("td", { className: "p-2", children: report.type }), _jsx("td", { className: "p-2 text-right", children: _jsxs("div", { className: "flex justify-end gap-2", children: [_jsx(Button, { variant: "ghost", size: "icon", onClick: () => onView(report), title: "View", children: _jsx(Eye, { className: "h-4 w-4" }) }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => onDownload(report), title: "Download", children: _jsx(Download, { className: "h-4 w-4" }) })] }) })] }, report.id))) })] }) }) })] }));
};
