import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ThemeToggle } from '@/components/ui/theme-toggle';
import { Menu } from 'lucide-react';
import { useSidebar } from '@/context/SidebarContext';
const MasterDashNavbar = ({ user }) => {
    const { isOpen, toggle } = useSidebar();
    return (_jsxs("header", { className: "flex items-center justify-between p-4 border-b border-slate-800 bg-gray-200", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: toggle, className: "p-2 rounded-md text-slate-700 hover:text-slate-900 hover:bg-slate-300", "aria-label": isOpen ? "Close sidebar" : "Open sidebar", children: _jsx(Menu, { className: "w-5 h-5" }) }), _jsx("h1", { className: "text-xl font-semibold", children: "Business Management Platform" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "flex gap-2", children: [_jsx("button", { className: "p-2 text-slate-700 hover:text-slate-900", children: _jsxs("svg", { className: "w-5 h-5", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M3 15a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-4Z" }), _jsx("path", { d: "M4 10h6" }), _jsx("path", { d: "M14 10h6" }), _jsx("path", { d: "M9 15v5" }), _jsx("path", { d: "M15 15v5" }), _jsx("path", { d: "M12 10V3" }), _jsx("path", { d: "M6 7l6-4 6 4" })] }) }), _jsx("button", { className: "p-2 text-slate-700 hover:text-slate-900", children: _jsxs("svg", { className: "w-5 h-5", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z" }), _jsx("path", { d: "m9 10 2 2 4-4" })] }) }), _jsx("button", { className: "p-2 text-slate-700 hover:text-slate-900", children: _jsxs("svg", { className: "w-5 h-5", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" }), _jsx("path", { d: "m17 8-5-5-5 5" }), _jsx("path", { d: "M12 3v12" })] }) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(ThemeToggle, {}), _jsx("div", { className: "w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white", children: user?.email?.charAt(0)?.toUpperCase() || 'U' }), _jsx("div", { className: "p-2 bg-slate-700 rounded-md text-white", children: user?.role || 'User' }), _jsx("div", { className: "w-8 h-8 flex items-center justify-center bg-blue-500 rounded-md", children: _jsx("span", { className: "text-white font-bold", children: "+" }) })] })] })] }));
};
export default MasterDashNavbar;
