import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
export function DefaultCustomerSettings() {
    return (_jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Default Settings" }), _jsx(CardDescription, { children: "Default settings for new customer profiles" })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Label, { htmlFor: "defaultStatus", children: "Default Status" }), _jsxs(Select, { defaultValue: "active", children: [_jsx(SelectTrigger, { id: "defaultStatus", children: _jsx(SelectValue, { placeholder: "Select status" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "active", children: "Active" }), _jsx(SelectItem, { value: "inactive", children: "Inactive" })] })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { htmlFor: "defaultCreditLimit", children: "Default Credit Limit" }), _jsx(Input, { id: "defaultCreditLimit", type: "number", defaultValue: "1000", placeholder: "e.g., 1000" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-1", children: [_jsx(Label, { htmlFor: "autoApprove", children: "Auto-approve New Customers" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Automatically approve new customer accounts" })] }), _jsx(Switch, { id: "autoApprove", defaultChecked: false })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-1", children: [_jsx(Label, { htmlFor: "emailNotifications", children: "Email Notifications" }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Send welcome email to new customers" })] }), _jsx(Switch, { id: "emailNotifications", defaultChecked: true })] })] }), _jsx("div", { className: "flex justify-end", children: _jsx(Button, { children: "Save Settings" }) })] })] }));
}
