import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PlatformLayout } from '@/components/layouts/PlatformLayout';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
const Beta1Dashboard = () => {
    const navigate = useNavigate();
    return (_jsx(PlatformLayout, { moduleTitle: "Data Platform Beta Dashboard", children: _jsxs("div", { className: "container mx-auto p-6", children: [_jsx("h1", { className: "text-2xl font-bold mb-4", children: "Data Platform Beta Dashboard" }), _jsxs(Card, { className: "mb-6", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Welcome to Beta 1" }) }), _jsxs(CardContent, { children: [_jsx("p", { className: "mb-4", children: "Welcome to the Beta 1 Dashboard. This dashboard provides an overview of the data platform capabilities." }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-6", children: [_jsx(Card, { className: "bg-blue-50", children: _jsxs(CardContent, { className: "p-4", children: [_jsx("h3", { className: "font-semibold text-blue-700", children: "Data Insights" }), _jsx("p", { className: "text-sm text-gray-600", children: "View and analyze your data insights" })] }) }), _jsx(Card, { className: "bg-green-50", children: _jsxs(CardContent, { className: "p-4", children: [_jsx("h3", { className: "font-semibold text-green-700", children: "Data Connections" }), _jsx("p", { className: "text-sm text-gray-600", children: "Manage your data source connections" })] }) }), _jsx(Card, { className: "bg-purple-50", children: _jsxs(CardContent, { className: "p-4", children: [_jsx("h3", { className: "font-semibold text-purple-700", children: "Reporting" }), _jsx("p", { className: "text-sm text-gray-600", children: "Access and customize reports" })] }) })] }), _jsx("div", { className: "mt-6", children: _jsx(Button, { onClick: () => navigate('/master'), children: "Back to Master Dashboard" }) })] })] })] }) }));
};
export default Beta1Dashboard;
