import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PlatformLayout } from '@/components/layouts/PlatformLayout';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, Bell, Settings } from 'lucide-react';
import { ragDashboardNavigation } from '@/components/rag-dashboard/config/dashboardNavigation';
const RAGDashboard = () => {
    const navigate = useNavigate();
    return (_jsx(PlatformLayout, { moduleTitle: "RAG Dashboard", navCategories: ragDashboardNavigation, children: _jsxs("div", { className: "container mx-auto p-4", children: [_jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-2xl font-bold flex items-center", children: [_jsx(AlertTriangle, { className: "h-6 w-6 mr-2 text-amber-500" }), "RAG System Dashboard"] }), _jsx("p", { className: "text-muted-foreground", children: "Monitor and manage system health and alerts" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: () => navigate('/dashboard/rag/alerts'), className: "flex items-center gap-1", children: [_jsx(Bell, { className: "h-4 w-4" }), "Alerts"] }), _jsxs(Button, { variant: "outline", size: "sm", onClick: () => navigate('/dashboard/rag/settings'), className: "flex items-center gap-1", children: [_jsx(Settings, { className: "h-4 w-4" }), "Settings"] })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6", children: [
                        { title: "Critical Issues", count: 3, color: "bg-red-100 text-red-800" },
                        { title: "Warnings", count: 7, color: "bg-amber-100 text-amber-800" },
                        { title: "Healthy Systems", count: 24, color: "bg-green-100 text-green-800" }
                    ].map((stat, i) => (_jsx(Card, { className: `${stat.color} border-0`, children: _jsxs(CardContent, { className: "pt-6", children: [_jsx("div", { className: "text-3xl font-bold", children: stat.count }), _jsx("p", { className: "font-medium", children: stat.title })] }) }, i))) }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "System Modules Status" }) }), _jsxs(CardContent, { children: [_jsx("p", { className: "mb-6", children: "This is a placeholder for the RAG dashboard content. In a complete implementation, this would show the status of different system modules." }), _jsx("div", { className: "border rounded-lg overflow-hidden", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Module" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Status" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Last Updated" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: [
                                                    { name: "Authentication", status: "Online", statusClass: "bg-green-100 text-green-800", updated: "5 mins ago" },
                                                    { name: "Database", status: "Warning", statusClass: "bg-amber-100 text-amber-800", updated: "2 mins ago" },
                                                    { name: "API Services", status: "Critical", statusClass: "bg-red-100 text-red-800", updated: "Just now" },
                                                    { name: "Storage", status: "Online", statusClass: "bg-green-100 text-green-800", updated: "10 mins ago" },
                                                ].map((module, i) => (_jsxs("tr", { children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm font-medium", children: module.name }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm", children: _jsx("span", { className: `px-2 py-1 rounded-full text-xs font-medium ${module.statusClass}`, children: module.status }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500", children: module.updated }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm", children: _jsx(Button, { variant: "outline", size: "sm", children: "View Details" }) })] }, i))) })] }) }), _jsx("div", { className: "mt-6", children: _jsx(Button, { onClick: () => navigate('/master'), children: "Back to Master Dashboard" }) })] })] })] }) }));
};
export default RAGDashboard;
