import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
const TradingSystemDashboard = () => {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "flex flex-col md:flex-row md:items-center md:justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold tracking-tight", children: "Trading System" }), _jsx("p", { className: "text-muted-foreground", children: "Inventory and Order Management Platform" })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsx(Button, { variant: "outline", onClick: () => navigate('/dashboard'), children: "Back to Dashboard" }) })] }), _jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Trading System Features" }), _jsx(CardDescription, { children: "Coming soon in our future releases" })] }), _jsx(CardContent, { children: _jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-muted-foreground", children: "The Trading System module will include features for inventory management, order processing, and logistics tracking." }), _jsxs("div", { className: "grid gap-4 md:grid-cols-3", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Inventory Management" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-muted-foreground", children: "Track stock levels, set reorder points, and manage inventory across locations." }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Order Processing" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-muted-foreground", children: "Create and manage customer orders, process payments, and handle fulfillment." }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Logistics" }) }), _jsx(CardContent, { children: _jsx("p", { className: "text-muted-foreground", children: "Manage shipping, track deliveries, and optimize your supply chain." }) })] })] })] }) })] })] }));
};
export default TradingSystemDashboard;
