import { 
  LayoutDashboard, Settings, Users, Briefcase, CalendarDays, BarChart, BellRing, ListTodo,
  Folder, MessageCircle, Database, Projector, Rss, Factory, Handshake, Shield,
  Zap, Globe, Bot, TrendingUp, Compass, Wrench, Package, Search,
  SquareKanban, Lightbulb, Bell, User, Building, FileText, Mail,
  ClipboardList, Layers, Monitor, Phone, Book, File, Megaphone,
  BarChart2, Clock, CheckCircle, XCircle, AlertCircle, Info, Key,
  Upload, Download, Plus, Minus, Edit, Trash2, ArrowRight, ArrowLeft,
  ChevronsRight, ChevronsLeft, ChevronsUp, ChevronsDown, Loader,
  Star, Heart, Link, ExternalLink, Menu, MoreVertical, MoreHorizontal,
  Home, Activity, ShoppingCart, CreditCard, DollarSign, Cloud, Sun, Moon, Laptop,
  Clipboard, PieChart, LineChart, TrendingDown, TrendingUp as TrendingUpIcon,
  Archive, FileCode, ImageIcon, Video, Mic, Headphones, Smile, Frown, Meh,
  Code, Terminal, GitBranch, GitCommit, GitMerge, GitPullRequest, Github, Gitlab,
  MessageSquare, Users as UsersIcon, Settings as SettingsIcon, BellRing as BellRingIcon,
  Briefcase as BriefcaseIcon, CalendarDays as CalendarDaysIcon, BarChart as BarChartIcon,
  ListTodo as ListTodoIcon,
  // Add other Lucide icons as needed based on your sidebarUtils.ts strings
} from 'lucide-react';

export const IconMap: Record<string, React.ElementType> = {
  dashboard: LayoutDashboard,
  settings: Settings,
  users: Users,
  briefcase: Briefcase,
  calendar: CalendarDays,
  reports: BarChart,
  notifications: BellRing,
  tasks: ListTodo,
  folder: Folder,
  communications: MessageCircle,
  data: Database,
  project: Projector, // Corrected from Project to Projector
  social: Rss,
  supplier: Factory,
  customer: Handshake,
  admin: Shield,
  automation: Zap,
  web: Globe,
  ai: Bot,
  trading: TrendingUp,
  dotx: Compass,
  wrench: Wrench,
  package: Package,
  search: Search,
  kanban: SquareKanban,
  lightbulb: Lightbulb,
  bell: Bell,
  user: User,
  building: Building,
  fileText: FileText,
  mail: Mail,
  clipboard: ClipboardList,
  layers: Layers,
  monitor: Monitor,
  phone: Phone,
  book: Book,
  file: File,
  megaphone: Megaphone,
  barChart: BarChart2,
  clock: Clock,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  key: Key,
  upload: Upload,
  download: Download,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash2,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronsRight: ChevronsRight,
  chevronsLeft: ChevronsLeft,
  chevronsUp: ChevronsUp,
  chevronsDown: ChevronsDown,
  loader: Loader,
  star: Star,
  heart: Heart,
  link: Link,
  externalLink: ExternalLink,
  menu: Menu,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  home: Home,
  activity: Activity,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  clipboardText: Clipboard, // Renamed to avoid conflict with ClipboardList
  pieChart: PieChart,
  lineChart: LineChart,
  trendingDown: TrendingDown,
  trendingUp: TrendingUpIcon,
  archive: Archive,
  fileCode: FileCode,
  imageIcon: ImageIcon,
  video: Video,
  mic: Mic,
  headphones: Headphones,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  code: Code,
  terminal: Terminal,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  gitMerge: GitMerge,
  gitPullRequest: GitPullRequest,
  github: Github,
  gitlab: Gitlab,
  messageSquare: MessageSquare,
  usersIcon: UsersIcon,
  settingsIcon: SettingsIcon,
  bellRingIcon: BellRingIcon,
  briefcaseIcon: BriefcaseIcon,
  calendarDaysIcon: CalendarDaysIcon,
  barChartIcon: BarChartIcon,
  listTodoIcon: ListTodoIcon,
};