
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbfiecswvhcskdswylpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZmllY3N3dmhjc2tkc3d5bHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4Mjg2MzIsImV4cCI6MjA4MTQwNDYzMn0.OUrL6yXrqzZySa3zNORvt4le_s4UoJAJCKXl2Aux_2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
