
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yunrxkbvbwyyhkxuhror.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bnJ4a2J2Ynd5eWhreHVocm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzQyNzQsImV4cCI6MjA2MzI1MDI3NH0.TrmoUxRPTXhL1AhioT-6MHpF5ydFXmOFE82T5neCLbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
